import React, { useState } from 'react';
import { 
  X, Camera, Sparkles, ArrowRight, ArrowLeft, CheckCircle2, 
  ShieldAlert, Tag, MapPin, Upload, AlertCircle 
} from 'lucide-react';
import { CATEGORIES } from '../data/mockData';
import { 
  aiSuggestCategory, 
  aiRecommendPrice, 
  aiGenerateDescription, 
  aiScanListingSafety, 
  aiCheckImageQuality 
} from '../utils/aiEngine';

export default function SellWizardModal({ isOpen, onClose, onPublishProduct, currentUser }) {
  const [step, setStep] = useState(1);

  // Form State
  const [images, setImages] = useState([
    'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=600&auto=format&fit=crop&q=80'
  ]);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [category, setCategory] = useState('furniture');
  const [price, setPrice] = useState('');
  const [negotiable, setNegotiable] = useState(true);
  const [condition, setCondition] = useState('Like New'); // New, Like New, Good, Fair
  const [brand, setBrand] = useState('');
  const [location, setLocation] = useState('North Campus Hostel Area');
  const [pickupAvailable, setPickupAvailable] = useState(true);
  const [deliveryAvailable, setDeliveryAvailable] = useState(false);
  const [hidePhone, setHidePhone] = useState(false);
  const [contactPreference, setContactPreference] = useState('Chat preferred');

  // AI states
  const [aiWorking, setAiWorking] = useState(false);

  if (!isOpen) return null;

  // Handlers for AI Tools
  const handleAutoSuggestCategory = () => {
    const suggested = aiSuggestCategory(title);
    setCategory(suggested);
  };

  const handleAutoGenerateDescription = () => {
    setAiWorking(true);
    setTimeout(() => {
      const gen = aiGenerateDescription(title, category, condition, brand);
      setDescription(gen);
      setAiWorking(false);
    }, 600);
  };

  const handleAutoRecommendPrice = () => {
    const rec = aiRecommendPrice(title, category, condition);
    setPrice(rec.recommended);
  };

  // Image upload simulation
  const handleAddSampleImage = () => {
    const samplePool = [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1534073828943-f801091bb18c?w=600&auto=format&fit=crop&q=80'
    ];
    if (images.length < 10) {
      setImages([...images, samplePool[images.length % samplePool.length]]);
    }
  };

  // Safety inspection report
  const safetyReport = aiScanListingSafety(title, description, Number(price) || 0);
  const imageQuality = aiCheckImageQuality(images.length);
  const priceRecommendation = aiRecommendPrice(title, category, condition);

  const handlePublish = () => {
    const newProd = {
      id: `prod-user-${Date.now()}`,
      title: title || 'Untitled Everyday Item',
      description: description || 'No description provided.',
      category,
      price: Number(price) || 500,
      originalPrice: (Number(price) || 500) * 2,
      negotiable,
      condition,
      brand: brand || 'Generic / Local',
      location,
      distanceKm: 0.8,
      pickupAvailable,
      deliveryAvailable,
      deliveryFee: deliveryAvailable ? 50 : 0,
      hidePhone,
      contactPreference,
      images,
      seller: {
        id: currentUser.id,
        name: currentUser.name,
        avatar: currentUser.avatar,
        rating: 5.0,
        reviewsCount: 1,
        verified: currentUser.verified,
        memberSince: 'Today',
        phone: currentUser.phone,
        salesCount: currentUser.salesCount || 0,
        responseTime: 'Instant'
      },
      featured: false,
      trending: false,
      createdAt: 'Just now',
      likesCount: 0,
      viewsCount: 1,
      status: 'active'
    };

    onPublishProduct(newProd);
    onClose();
  };

  return (
    <div className="modal-overlay">
      <div className="bottom-sheet" style={{ height: '94%', maxHeight: '94%' }}>
        <div className="sheet-handle"></div>

        {/* Modal Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
          <div>
            <span style={{ fontSize: '0.72rem', fontWeight: 800, color: 'var(--primary)', textTransform: 'uppercase' }}>
              Step {step} of 7
            </span>
            <h3 style={{ fontSize: '1.15rem', fontWeight: 800 }}>
              {step === 1 && 'Upload Photos'}
              {step === 2 && 'Title & Description'}
              {step === 3 && 'Category & Condition'}
              {step === 4 && 'Set Price & Negotiability'}
              {step === 5 && 'Location & Delivery'}
              {step === 6 && 'AI Safety Check'}
              {step === 7 && 'Preview & Publish'}
            </h3>
          </div>

          <button onClick={onClose} style={{ background: 'var(--bg-tertiary)', border: 'none', width: '32px', height: '32px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <X size={18} />
          </button>
        </div>

        {/* Progress Bar */}
        <div style={{ height: '4px', background: 'var(--border-light)', borderRadius: '4px', overflow: 'hidden', marginBottom: '16px' }}>
          <div style={{ width: `${(step / 7) * 100}%`, height: '100%', background: 'linear-gradient(90deg, #2563eb, #3b82f6)', transition: 'width 0.3s ease' }}></div>
        </div>

        {/* STEP CONTENT */}
        <div style={{ flex: 1, overflowY: 'auto', paddingRight: '4px' }}>
          {/* STEP 1: Upload Photos */}
          {step === 1 && (
            <div>
              <p style={{ fontSize: '0.84rem', color: 'var(--text-muted)', marginBottom: '12px' }}>
                Upload up to 10 photos. Clear images get sold 3x faster!
              </p>

              {/* Photos Grid */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '10px', marginBottom: '16px' }}>
                {images.map((img, idx) => (
                  <div key={idx} style={{ position: 'relative', height: '90px', borderRadius: '12px', overflow: 'hidden', border: '1px solid var(--border-light)' }}>
                    <img src={img} alt="upload" style={{ width: '100%', height: '100%', objectFit: 'cover' }} />
                    <button 
                      onClick={() => setImages(images.filter((_, i) => i !== idx))}
                      style={{ position: 'absolute', top: '4px', right: '4px', background: 'rgba(0,0,0,0.6)', color: '#fff', border: 'none', width: '22px', height: '22px', borderRadius: '50%', cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                    >
                      <X size={12} />
                    </button>
                  </div>
                ))}

                {images.length < 10 && (
                  <button 
                    onClick={handleAddSampleImage}
                    style={{ height: '90px', border: '2px dashed var(--primary)', borderRadius: '12px', background: 'var(--primary-light)', color: 'var(--primary)', cursor: 'pointer', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '4px' }}
                  >
                    <Camera size={22} />
                    <span style={{ fontSize: '0.72rem', fontWeight: 700 }}>+ Add Photo</span>
                  </button>
                )}
              </div>

              {/* AI Image Quality Scanner Box */}
              <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-light)', borderRadius: 'var(--radius-md)', padding: '12px', display: 'flex', gap: '10px', alignItems: 'center' }}>
                <Sparkles size={20} color="var(--primary)" />
                <div>
                  <div style={{ fontSize: '0.82rem', fontWeight: 800 }}>AI Quality Check: {imageQuality.status} ({imageQuality.score}/100)</div>
                  <div style={{ fontSize: '0.76rem', color: 'var(--text-muted)' }}>{imageQuality.tip}</div>
                </div>
              </div>
            </div>
          )}

          {/* STEP 2: Title & Description */}
          {step === 2 && (
            <div>
              <div className="form-group">
                <label className="form-label">Product Title</label>
                <input 
                  type="text" 
                  className="input-field" 
                  placeholder="e.g. Minimalist Wooden Study Table" 
                  value={title} 
                  onChange={(e) => setTitle(e.target.value)} 
                />
              </div>

              <div className="form-group">
                <label className="form-label">Brand / Manufacturer (Optional)</label>
                <input 
                  type="text" 
                  className="input-field" 
                  placeholder="e.g. IKEA, Pigeon, boAt" 
                  value={brand} 
                  onChange={(e) => setBrand(e.target.value)} 
                />
              </div>

              <div className="form-group">
                <div className="form-label">
                  <span>Product Description</span>
                  <button 
                    type="button" 
                    onClick={handleAutoGenerateDescription}
                    disabled={aiWorking || !title}
                    style={{ background: 'none', border: 'none', color: 'var(--primary)', fontWeight: 700, fontSize: '0.76rem', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '4px' }}
                  >
                    <Sparkles size={13} /> {aiWorking ? 'Generating...' : 'AI Auto-Generate'}
                  </button>
                </div>
                <textarea 
                  rows={4} 
                  className="input-field" 
                  placeholder="Describe condition, age, reasons for selling..." 
                  value={description} 
                  onChange={(e) => setDescription(e.target.value)}
                />
              </div>
            </div>
          )}

          {/* STEP 3: Category & Condition */}
          {step === 3 && (
            <div>
              <div className="form-group">
                <div className="form-label">
                  <span>Select Category</span>
                  <button 
                    type="button"
                    onClick={handleAutoSuggestCategory}
                    disabled={!title}
                    style={{ background: 'none', border: 'none', color: 'var(--primary)', fontWeight: 700, fontSize: '0.76rem', cursor: 'pointer' }}
                  >
                    <Sparkles size={13} /> AI Category Auto-Tag
                  </button>
                </div>

                <select 
                  className="input-field" 
                  value={category} 
                  onChange={(e) => setCategory(e.target.value)}
                >
                  {CATEGORIES.map(c => (
                    <option key={c.id} value={c.id}>{c.name}</option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Item Condition</label>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '8px' }}>
                  {['New', 'Like New', 'Good', 'Fair'].map(cond => (
                    <button
                      key={cond}
                      type="button"
                      onClick={() => setCondition(cond)}
                      style={{
                        padding: '10px', border: '1px solid var(--border-light)', borderRadius: '10px',
                        fontSize: '0.82rem', fontWeight: 700, cursor: 'pointer',
                        background: condition === cond ? 'var(--primary)' : 'var(--bg-secondary)',
                        color: condition === cond ? '#fff' : 'var(--text-main)'
                      }}
                    >
                      {cond}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* STEP 4: Set Price */}
          {step === 4 && (
            <div>
              {/* AI Recommendation Tool Card */}
              <div style={{ background: 'var(--primary-light)', border: '1px solid var(--primary-ring)', borderRadius: 'var(--radius-md)', padding: '14px', marginBottom: '16px' }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                  <span style={{ fontSize: '0.82rem', fontWeight: 800, color: 'var(--primary)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    <Sparkles size={15} /> AI Price Intelligence Tool
                  </span>
                  <button 
                    onClick={handleAutoRecommendPrice}
                    style={{ background: 'var(--primary)', color: '#fff', border: 'none', padding: '4px 10px', borderRadius: '10px', fontSize: '0.72rem', fontWeight: 700, cursor: 'pointer' }}
                  >
                    Apply ₹{priceRecommendation.recommended}
                  </button>
                </div>
                <div style={{ fontSize: '0.76rem', color: 'var(--text-secondary)' }}>
                  Suggested Range: <strong>₹{priceRecommendation.min} - ₹{priceRecommendation.max}</strong>
                </div>
              </div>

              <div className="form-group">
                <label className="form-label">Selling Price (₹)</label>
                <input 
                  type="number" 
                  className="input-field" 
                  placeholder="e.g. 1500" 
                  value={price} 
                  onChange={(e) => setPrice(e.target.value)} 
                  style={{ fontSize: '1.2rem', fontWeight: 800, color: 'var(--primary)' }}
                />
              </div>

              <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.86rem', fontWeight: 700, cursor: 'pointer', marginTop: '10px' }}>
                <input 
                  type="checkbox" 
                  checked={negotiable} 
                  onChange={(e) => setNegotiable(e.target.checked)}
                  style={{ accentColor: 'var(--primary)' }}
                />
                Price is Negotiable
              </label>
            </div>
          )}

          {/* STEP 5: Location & Delivery */}
          {step === 5 && (
            <div>
              <div className="form-group">
                <label className="form-label">Pickup Location Neighborhood</label>
                <input 
                  type="text" 
                  className="input-field" 
                  placeholder="e.g. North Campus Hostel Block A" 
                  value={location} 
                  onChange={(e) => setLocation(e.target.value)} 
                />
              </div>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', margin: '14px 0' }}>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.86rem', fontWeight: 600 }}>
                  <input type="checkbox" checked={pickupAvailable} onChange={(e) => setPickupAvailable(e.target.checked)} style={{ accentColor: 'var(--primary)' }} />
                  Self-Pickup Available
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.86rem', fontWeight: 600 }}>
                  <input type="checkbox" checked={deliveryAvailable} onChange={(e) => setDeliveryAvailable(e.target.checked)} style={{ accentColor: 'var(--primary)' }} />
                  Local Delivery Available (₹50 fee)
                </label>
                <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '0.86rem', fontWeight: 600 }}>
                  <input type="checkbox" checked={hidePhone} onChange={(e) => setHidePhone(e.target.checked)} style={{ accentColor: 'var(--primary)' }} />
                  Hide My Phone Number (Chat only contact)
                </label>
              </div>
            </div>
          )}

          {/* STEP 6: AI Safety Check */}
          {step === 6 && (
            <div>
              <div style={{ textAlign: 'center', padding: '16px', background: 'var(--bg-secondary)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border-light)', marginBottom: '16px' }}>
                {safetyReport.riskScore === 0 ? (
                  <CheckCircle2 size={42} color="#10b981" style={{ margin: '0 auto 10px auto' }} />
                ) : (
                  <AlertCircle size={42} color={safetyReport.badgeColor} style={{ margin: '0 auto 10px auto' }} />
                )}
                <h4 style={{ fontSize: '1.05rem', fontWeight: 800 }}>AI Scam & Quality Inspection</h4>
                <div style={{ fontSize: '0.82rem', fontWeight: 700, color: safetyReport.badgeColor, marginTop: '4px' }}>
                  Result: {safetyReport.status} ({100 - safetyReport.riskScore}% Trust Score)
                </div>
              </div>

              {safetyReport.flags.length > 0 && (
                <div style={{ background: 'rgba(239, 68, 68, 0.08)', border: '1px solid rgba(239, 68, 68, 0.3)', padding: '12px', borderRadius: '12px', marginBottom: '16px' }}>
                  <strong style={{ fontSize: '0.82rem', color: '#dc2626' }}>Flagged Safety Items:</strong>
                  <ul style={{ fontSize: '0.78rem', color: 'var(--text-secondary)', paddingLeft: '18px', marginTop: '4px' }}>
                    {safetyReport.flags.map((f, i) => <li key={i}>{f}</li>)}
                  </ul>
                </div>
              )}

              <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                {safetyReport.recommendation}
              </p>
            </div>
          )}

          {/* STEP 7: Preview & Publish */}
          {step === 7 && (
            <div>
              <div className="product-card" style={{ cursor: 'default', marginBottom: '16px' }}>
                <div className="product-img-wrapper" style={{ height: '180px' }}>
                  <img src={images[0]} alt="preview" className="product-img" />
                </div>
                <div className="product-info">
                  <div className="product-title" style={{ fontSize: '1rem' }}>{title || 'Untitled Listing'}</div>
                  <div className="product-price" style={{ fontSize: '1.2rem' }}>₹{price || 0}</div>
                  <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', marginTop: '4px' }}>
                    {category} • {condition} • {location}
                  </div>
                </div>
              </div>

              <div style={{ background: 'var(--bg-secondary)', padding: '12px', borderRadius: '12px', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                By tapping Publish, your listing will be live instantly for buyers in your area!
              </div>
            </div>
          )}
        </div>

        {/* STEP CONTROLLER BUTTONS */}
        <div style={{ display: 'flex', gap: '10px', marginTop: '16px', borderTop: '1px solid var(--border-light)', paddingTop: '12px' }}>
          {step > 1 && (
            <button 
              onClick={() => setStep(step - 1)}
              className="btn-secondary" 
              style={{ flex: 1 }}
            >
              <ArrowLeft size={16} /> Back
            </button>
          )}

          {step < 7 ? (
            <button 
              onClick={() => setStep(step + 1)}
              className="btn-primary" 
              style={{ flex: 2 }}
            >
              Next Step <ArrowRight size={16} />
            </button>
          ) : (
            <button 
              onClick={handlePublish}
              className="btn-primary" 
              style={{ flex: 2, background: 'linear-gradient(135deg, #10b981, #059669)' }}
            >
              Publish Listing Now <CheckCircle2 size={16} />
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
